services:
  app:
    build: .
    container_name: meeting_service
    restart: unless-stopped
    ports:
      - "4004:4004"
    # Supprime ou commente cette ligne si tu n'as pas de fichier .env
    # env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db-meeting
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
      MYSQL_DATABASE: meeting_db
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
