services:
  app:
    build: .
    container_name: fees_service
    restart: unless-stopped
    ports:
      - "4003:4003"
    # Supprime ou commente cette ligne si tu n'as pas de fichier .env
    # env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db-fees
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: fees_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:	fees-db-data

networks:
  app-network:
