services:
  app:
    build: .
    container_name: syndic_service
    restart: unless-stopped
    ports:
      - "4002:4002"
    # Supprime ou commente cette ligne si tu n'as pas de fichier .env
    # env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db-syndic
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: syndic_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
