version: "3.9"

services:
  app:
    build: .
    container_name: node-app
    restart: unless-stopped
    ports:
      - "4001:4001"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
